name: "Read file contents"

on: 
  workflow_dispatch:
    inputs:
      FILE:
        description: 'Give a file as input' 
        type: file  
        required: true

env:
  FILE: ${{ github.event.inputs.FILE }}
        
jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: File contents
        run: echo "${ {env.FILE}.outputs.contents }"